version: '3.8'

services:
    opensearch_250:
        container_name: "opensearch_250"
        build:
            context: ./images/opensearch/2.5.0
            dockerfile: ./Dockerfile
        restart: unless-stopped
        volumes:
            - opensearch_250:/usr/share/opensearch/data
        ports:
            - "49201:9200"
            - "49301:9300"
        environment:
            - "discovery.type=single-node"
            - "cluster.routing.allocation.disk.threshold_enabled=false"
            - "index.blocks.read_only_allow_delete"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1G
        networks:
            - magento-network

    elasticsearch_717:
        container_name: "elasticsearch_717"
        build:
            context: ./images/elasticsearch/7.17.7
            dockerfile: ./Dockerfile
        restart: unless-stopped
        volumes:
            - elasticsearch_717:/usr/share/elasticsearch/data
        ports:
            - "49200:9200"
            - "49300:9300"
        environment:
            - "discovery.type=single-node"
            - "cluster.routing.allocation.disk.threshold_enabled=false"
            - "index.blocks.read_only_allow_delete"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1G
        networks:
            - magento-network

    mysql_80:
        container_name: "mysql_80"
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'main'
            MYSQL_USER: 'magento'
            MYSQL_PASSWORD: 'magento'
            MYSQL_ROOT_PASSWORD: 'magento'
        ports:
            - "43306:3306"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1G
        volumes:
            - mysql_80:/var/lib/mysql
        networks:
            - magento-network

    php_74:
        container_name: "php_74"
        build:
            context: ./images/php/7.4
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - "49000:9000"
        volumes:
            - "${DOCUMENT_ROOT}:/var/www/html"
            - ./code/adminer:/var/www/html/adminer
        networks:
            - magento-network

    php_82:
        container_name: "php_82"
        build:
            context: ./images/php/8.2
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - "49001:9000"
        volumes:
            - "${DOCUMENT_ROOT}:/var/www/html"
            - ./code/adminer:/var/www/html/adminer
        networks:
            - magento-network

    nginx:
        container_name: "nginx"
        build:
            context: ./images/nginx
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - "${DOCUMENT_ROOT}:/var/www/html"
            - ./code/adminer:/var/www/html/adminer
            - ./config/nginx-virtual-hosts.conf:/etc/nginx/conf.d/default.conf
            - ./config/magento-virtual-host.conf:/tmp/nginx.conf
        networks:
            - magento-network

networks:
    magento-network:
        driver: bridge
        enable_ipv6: false

volumes:
    opensearch_250:
    elasticsearch_717:
    mysql_80:
