version: '3.8'

services:
    opensearch_250:
        container_name: "opensearch_250"
        build:
            context: ./images/opensearch/2.5.0
            dockerfile: ./Dockerfile
        restart: unless-stopped
        volumes:
            - opensearch_250:/usr/share/opensearch/data
        ports:
            - "49201:9200"
            - "49301:9300"
        environment:
            - "discovery.type=single-node"
            - "cluster.routing.allocation.disk.threshold_enabled=false"
            - "index.blocks.read_only_allow_delete"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1G
        networks:
            - magento-network

    elasticsearch_717:
        container_name: "elasticsearch_717"
        build:
            context: ./images/elasticsearch/7.17.7
            dockerfile: ./Dockerfile
        restart: unless-stopped
        volumes:
            - elasticsearch_717:/usr/share/elasticsearch/data
        ports:
            - "49200:9200"
            - "49300:9300"
        environment:
            - "discovery.type=single-node"
            - "cluster.routing.allocation.disk.threshold_enabled=false"
            - "index.blocks.read_only_allow_delete"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1G
        networks:
            - magento-network

    mysql_80:
        container_name: "mysql_80"
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'main'
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        ports:
            - "43306:3306"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 1G
        volumes:
            - mysql_80:/var/lib/mysql
        networks:
            - magento-network

    php_74:
        container_name: "php_74"
        build:
            context: ./images/php/7.4
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - "49000:9000"
        volumes:
            - "${CODEBASE_PARENT_DIRECTORY}:/app"
            - ./code/adminer:/var/www/adminer
        networks:
            - magento-network

    php_82:
        container_name: "php_82"
        build:
            context: ./images/php/8.2
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - "49001:9000"
        volumes:
            - "${CODEBASE_PARENT_DIRECTORY}:/app"
            - ./code/adminer:/var/www/adminer
        networks:
            - magento-network

    nginx:
        container_name: "nginx"
        build:
            context: ./images/nginx
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./code/adminer:/var/www/adminer
            - "${CODEBASE_PARENT_DIRECTORY}:/app"
            - "${CODEBASE_PARENT_DIRECTORY}/nginx/virtual-hosts:/etc/nginx/magento/virtual-hosts"
            - "${CODEBASE_PARENT_DIRECTORY}/nginx/magento-config:/etc/nginx/magento/magento-config"
        networks:
            - magento-network
        depends_on:
            - php_74
            - php_82

networks:
    magento-network:
        driver: bridge
        enable_ipv6: false

volumes:
    opensearch_250:
    elasticsearch_717:
    mysql_80:
